/**
 * Centralized type definitions for all Concourse AI Agent data models.
 *
 * These types define the canonical shape of Firestore documents consumed
 * by the frontend. All agent pages and hooks should import from here
 * rather than defining inline types.
 */

// ──────────────────────────────────────────────
// Pulse Agent
// ──────────────────────────────────────────────

/** Live pulse data metrics representing overall stadium occupancy and throughput. */
export interface PulseData {
  /** Current stadium capacity percentage (e.g. 85 for 85%). */
  occupancy: number;
  /** Inbound fan flow rate per minute. */
  flowRate: number;
  /** Active flagged security or crowd incidents. */
  activeIncidents: number;
  /** ISO timestamp of last metric calculation. */
  timestamp: string;
}

// ──────────────────────────────────────────────
// Transit Agent
// ──────────────────────────────────────────────

/** An individual transit schedule item (train or bus). */
export interface TrainSchedule {
  /** Name of the line or route. */
  line: string;
  /** Human-readable status (e.g. 'On Time', 'Delayed'). */
  status: string;
  /** ETA formatted string. */
  time: string;
  /** Tailwind UI color class for status indicators. */
  color: string;
}

/** Aggregate live transit schedules for external logistics. */
export interface TransitData {
  /** Array of active vehicle arrivals. */
  trains: TrainSchedule[];
}

// ──────────────────────────────────────────────
// Access Agent
// ──────────────────────────────────────────────

/** Individual reasoning log from the Access control agent. */
export interface AccessLog {
  /** Categorical event type. */
  type: 'sensor' | 'group' | 'agent' | 'conclusion';
  /** Primary event description. */
  message: string;
  /** Additional diagnostic detail. */
  submessage?: string;
  /** Material symbol icon string. */
  icon: string;
  /** Tailwind text color class. */
  color: string;
  /** Tailwind background color class. */
  bg: string;
  /** ISO timestamp of the event. */
  time: string;
}

/** Operational metrics for ticket scanning and perimeter security. */
export interface AccessData {
  /** Count of valid credential scans. */
  validScans: number;
  /** Count of rejected or invalid scans. */
  invalidAttempts: number;
  /** Count of VIP or special clearance scans. */
  vipClearances: number;
  /** Number of active perimeter breaches detected. */
  detectedBreaches: number;
  /** AI-generated reasoning logs explaining access anomalies. */
  reasoningTrail: AccessLog[];
  /** ISO timestamp of last update. */
  timestamp: string;
}

// ──────────────────────────────────────────────
// Wayfinder Agent
// ──────────────────────────────────────────────

/** Dynamic pathfinding and crowd flow log generated by AI. */
export interface WayfinderLog {
  /** Categorical log type. */
  type: string;
  /** Short headline for the log. */
  title: string;
  /** Primary description. */
  message: string;
  /** Material symbol icon string. */
  icon: string;
  /** Tailwind text color class. */
  color: string;
  /** Tailwind background color class. */
  bg: string;
  /** ISO timestamp of the event. */
  time: string;
}

/** Crowd flow optimization and rerouting metrics. */
export interface WayfinderData {
  /** True if the agent is actively rerouting crowds. */
  activeReroute: boolean;
  /** Current highest-density gate bottleneck. */
  targetGate: string;
  /** Egress flow rate per minute. */
  flowRate: number;
  /** Maximum safe capacity of the target zone. */
  capacityLimit: number;
  /** AI-generated logs explaining reroute decisions. */
  reasoningTrail: WayfinderLog[];
  /** ISO timestamp of last update. */
  timestamp: string;
}

// ──────────────────────────────────────────────
// Polyglot Agent
// ──────────────────────────────────────────────

/** A live translated chat message from the communication mesh. */
export interface PolyglotChat {
  /** Name of the entity sending the message. */
  sender: string;
  /** Source locale code (e.g. 'ES-AR'). */
  lang: string;
  /** Original untranslated message. */
  source: string;
  /** English translated message. */
  translated: string;
  /** AI translation confidence score (0-100). */
  conf: number;
  /** UI alignment (left or right). */
  align: 'left' | 'right';
  /** True if the message was sent by the automated agent. */
  isAgent?: boolean;
  /** ISO timestamp of the message. */
  time: string;
}

/** Real-time translation and emergency broadcast metrics. */
export interface PolyglotData {
  /** Number of active communication nodes or radios. */
  activeNodes: number;
  /** Most recent live chat streams. */
  liveTranslations: PolyglotChat[];
  /** ISO timestamp of last update. */
  timestamp: string;
}

// ──────────────────────────────────────────────
// Verde Agent
// ──────────────────────────────────────────────

/** Environmental sustainability and energy management log. */
export interface VerdeLog {
  /** ISO timestamp of the event. */
  time: string;
  /** Primary description or recommendation. */
  message: string;
  /** Categorizes the entry as a passive log or actionable recommendation. */
  type: 'log' | 'recommendation';
  /** Additional diagnostic detail. */
  submessage?: string;
  /** Projected operational savings. */
  savings?: string;
}

/** Live sustainability metrics (HVAC, power, water). */
export interface VerdeData {
  /** Current grid power draw in Megawatts. */
  powerDraw: number;
  /** Current water usage in gallons/minute. */
  waterUsage: number;
  /** Estimated carbon footprint reduction. */
  carbonFootprint: string;
  /** AI-generated logs explaining energy optimizations. */
  reasoningTrail: VerdeLog[];
  /** ISO timestamp of last update. */
  timestamp: string;
}
